# Generated by Django 6.1.1 on 2026-09-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteRequest',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('citizen_name', models.CharField(max_length=100)),
                ('collector', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
