# Generated by Django 6.1.1 on 2026-09-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('collector', 'Collector'), ('admin', 'Admin')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
