# Generated by Django 6.1.1 on 2026-09-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_otprecord_useraccount_address_useraccount_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
